== Tekton with ArgoCD

=== Create secrets for SSH GitHub

This is one way to create a SSH key, that will be added to GitHub.

----
ssh-keygen -t rsa -b 4096 -C "tekton@shikanga.co.uk"
# save as tekton / tekton.pub
# add tekton.pub contents to GitHub
----

==== Create secret YAML from ssh key contents

----
cat tekton | base64 -w 0; echo
----

Followed by

----
cat > tekton-git-ssh-secret.yaml << EOM
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <base64 data>
EOM
----

Then execute

----
kubectl apply -f tekton-git-ssh-secret.yaml
----

=== Create secrets for Docker Registry

----
cat ~/.docker/config.json | base64 -w 0; echo
----

Followed by

----
cat > regsecret.yaml << EOM
kind: Secret
apiVersion: v1
metadata:
  name: regsecret
data:
  .dockercfg: <base 64 data>
type: kubernetes.io/dockercfg
EOM
----

Then execute

----
kubectl apply -n tekton-pipelines -f regsecret.yaml
----


== Download & Install Istio on the Raspberry Pi 4+

. Download and extract the latest release automatically
----
curl -L https://istio.io/downloadIstio | sh -
----

[start=2]
. Move to the Istio package directory. For example, if the package is `istio-1.12.1:`
----
cd istio-1.12.1
----

[start=3]
. Add the istioctl client to your path (Linux or macOS):
----
export PATH=$PWD/bin:$PATH
----

[start=4]
. Install the arm-64 version of Istio with the command below:
----
istioctl install --set hub=docker.io/querycapistio
----



== Dealing with stuck namespaces

Sometimes when dealing with K8s, you might find yourself in a position where you cannot delete a namespace. The namespace, seems to be stuck in the "Terminating" phase

https://www.ibm.com/docs/en/cloud-private/3.2.0?topic=console-namespace-is-stuck-in-terminating-state


[start=1]
. create a directory to work in
----
mkdir stuck-namespaces

cd stuck-namespaces

kubectl get namespace <terminating-namespace> -o json >tmp.json
----

[start=2]
. Edit your tmp.json file. Remove the kubernetes value from the finalizers field and save the file.
----
nano tmp.json
----

[start=3]
. To set a temporary proxy IP and port, run the following command. Be sure to keep your terminal window open until you delete the stuck namespace:
----
kubectl proxy --port=9999
----

[start=4]
. From a new terminal window, make an API call with your temporary proxy IP and port:
----
curl -k -H "Content-Type: application/json" -X PUT --data-binary @tmp.json http://127.0.0.1:9999/api/v1/namespaces/<terminating-namespace>/finalize
----

[start=5]
. Verify that the terminating namespace is removed:
----
 kubectl get namespaces
 ----