=== eclipse-microprofile

Optimizing Enterprise Java for a Microservices Architecture

=== Setup of a Local Kubernetes and Istio Dev Environment

In order to build cloud-native applications and microservices, it’s very convenient to have a local https://kubernetes.io/[Kubernetes] cluster and https://istio.io/[Istio] running locally. This article describes how to install these components and some additional tools like https://www.kiali.io/[Kiali].

==== Minikube

I’ve chosen is https://kubernetes.io/docs/setup/minikube/[Minikube] which runs a single-node Kubernetes cluster inside a VM on your development machine.

===== Install and Set Up kubectl on Ubuntu

I highly recommend using `snap package manager`, kubectl is available as a snap application.
----
snap install kubectl --classic

kubectl version
----

===== Install MiniKube

One first needs to check if virtualization is supported on their Linux distro. Run the following command and verify that the output is non-empty:
----
$ grep -E --color 'vmx|svm' /proc/cpuinfo
----

Verify that `kubectl` was installed correctly

===== Install a Hypervisor
* Update your system with the latest version. You can do this by running the following commands:
----
$ sudo apt-get update -y
$ sudo apt-get upgrade -y
----
* Next, install some required packages with the following command:
----
$ sudo apt-get install curl wget apt-transport-https -y
----
* Follow the process below to install latest version of VirtualBox.

** Add Oracle VirtualBox’s repository to your list of repositories. You add its GPG key so that your system trusts this repository. Now when you install VirtualBox, it will be installed from Oracle’s repository instead of Ubuntu’s repository. If there is a new version released, VirtualBox install will be updated along with the system updates.

*** First, add the key for the repository, using the following command:
----
$ wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
----

** Now add the Oracle VirtualBox repository to the list of repositories using this command:
----
$ sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib"
----

** Type `sudo apt install virtualbox–` and hit tab to see the various VirtualBox versions available for installation and then select one of them by typing it completely.
----
$ sudo apt update && sudo apt install virtualbox-6.1
----

** Use the command below if you need to `remove` VirtualBox from Ubuntu
----
$ sudo apt remove virtualbox virtualbox-*
----