apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-git-ops
  namespace: myapp-git-ops
spec:
  selector:
    matchLabels:
      app: myapp-git-ops
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-git-ops
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
