apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-git-ops
  namespace: myapp-git-ops
spec:
  selector:
    matchLabels:
      app: myapp-git-ops
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-git-ops
    spec:
      containers:
      - name: myapp-git-ops
        image: siralexander/knote-java-arm64:1.0.0
        ports:
        - containerPort: 8080
